#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="quanly")]
	public partial class DTBdbmlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_lophoc(tbl_lophoc instance);
    partial void Updatetbl_lophoc(tbl_lophoc instance);
    partial void Deletetbl_lophoc(tbl_lophoc instance);
    partial void Inserttbl_sinhvien(tbl_sinhvien instance);
    partial void Updatetbl_sinhvien(tbl_sinhvien instance);
    partial void Deletetbl_sinhvien(tbl_sinhvien instance);
    #endregion
		
		public DTBdbmlDataContext() : 
				base(global::Project.Properties.Settings.Default.quanlyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DTBdbmlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DTBdbmlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DTBdbmlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DTBdbmlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_lophoc> tbl_lophocs
		{
			get
			{
				return this.GetTable<tbl_lophoc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_sinhvien> tbl_sinhviens
		{
			get
			{
				return this.GetTable<tbl_sinhvien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lophoc")]
	public partial class tbl_lophoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _malop;
		
		private string _tenlop;
		
		private string _ghichu;
		
		private EntitySet<tbl_sinhvien> _tbl_sinhviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmalopChanging(string value);
    partial void OnmalopChanged();
    partial void OntenlopChanging(string value);
    partial void OntenlopChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    #endregion
		
		public tbl_lophoc()
		{
			this._tbl_sinhviens = new EntitySet<tbl_sinhvien>(new Action<tbl_sinhvien>(this.attach_tbl_sinhviens), new Action<tbl_sinhvien>(this.detach_tbl_sinhviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenlop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenlop
		{
			get
			{
				return this._tenlop;
			}
			set
			{
				if ((this._tenlop != value))
				{
					this.OntenlopChanging(value);
					this.SendPropertyChanging();
					this._tenlop = value;
					this.SendPropertyChanged("tenlop");
					this.OntenlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lophoc_tbl_sinhvien", Storage="_tbl_sinhviens", ThisKey="malop", OtherKey="malop")]
		public EntitySet<tbl_sinhvien> tbl_sinhviens
		{
			get
			{
				return this._tbl_sinhviens;
			}
			set
			{
				this._tbl_sinhviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_sinhviens(tbl_sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lophoc = this;
		}
		
		private void detach_tbl_sinhviens(tbl_sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lophoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sinhvien")]
	public partial class tbl_sinhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mssv;
		
		private System.DateTime _ngaysinh;
		
		private string _malop;
		
		private string _hovaten;
		
		private bool _gioitinh;
		
		private string _ghichu;
		
		private EntityRef<tbl_lophoc> _tbl_lophoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmssvChanging(int value);
    partial void OnmssvChanged();
    partial void OnngaysinhChanging(System.DateTime value);
    partial void OnngaysinhChanged();
    partial void OnmalopChanging(string value);
    partial void OnmalopChanged();
    partial void OnhovatenChanging(string value);
    partial void OnhovatenChanged();
    partial void OngioitinhChanging(bool value);
    partial void OngioitinhChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    #endregion
		
		public tbl_sinhvien()
		{
			this._tbl_lophoc = default(EntityRef<tbl_lophoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mssv", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int mssv
		{
			get
			{
				return this._mssv;
			}
			set
			{
				if ((this._mssv != value))
				{
					this.OnmssvChanging(value);
					this.SendPropertyChanging();
					this._mssv = value;
					this.SendPropertyChanged("mssv");
					this.OnmssvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="DateTime NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					if (this._tbl_lophoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hovaten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hovaten
		{
			get
			{
				return this._hovaten;
			}
			set
			{
				if ((this._hovaten != value))
				{
					this.OnhovatenChanging(value);
					this.SendPropertyChanging();
					this._hovaten = value;
					this.SendPropertyChanged("hovaten");
					this.OnhovatenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="Bit NOT NULL")]
		public bool gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(100)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lophoc_tbl_sinhvien", Storage="_tbl_lophoc", ThisKey="malop", OtherKey="malop", IsForeignKey=true)]
		public tbl_lophoc tbl_lophoc
		{
			get
			{
				return this._tbl_lophoc.Entity;
			}
			set
			{
				tbl_lophoc previousValue = this._tbl_lophoc.Entity;
				if (((previousValue != value) 
							|| (this._tbl_lophoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_lophoc.Entity = null;
						previousValue.tbl_sinhviens.Remove(this);
					}
					this._tbl_lophoc.Entity = value;
					if ((value != null))
					{
						value.tbl_sinhviens.Add(this);
						this._malop = value.malop;
					}
					else
					{
						this._malop = default(string);
					}
					this.SendPropertyChanged("tbl_lophoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
